#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 网络招聘系统
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="网络招聘")]
	public partial class BSDataClasseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertBS_person(BS_person instance);
    partial void UpdateBS_person(BS_person instance);
    partial void DeleteBS_person(BS_person instance);
    partial void InsertBS_job_resume(BS_job_resume instance);
    partial void UpdateBS_job_resume(BS_job_resume instance);
    partial void DeleteBS_job_resume(BS_job_resume instance);
    partial void InsertBS_rwork(BS_rwork instance);
    partial void UpdateBS_rwork(BS_rwork instance);
    partial void DeleteBS_rwork(BS_rwork instance);
    partial void InsertBS_redu(BS_redu instance);
    partial void UpdateBS_redu(BS_redu instance);
    partial void DeleteBS_redu(BS_redu instance);
    partial void InsertBS_job(BS_job instance);
    partial void UpdateBS_job(BS_job instance);
    partial void DeleteBS_job(BS_job instance);
    partial void InsertBS_c_info(BS_c_info instance);
    partial void UpdateBS_c_info(BS_c_info instance);
    partial void DeleteBS_c_info(BS_c_info instance);
    partial void InsertBS_company(BS_company instance);
    partial void UpdateBS_company(BS_company instance);
    partial void DeleteBS_company(BS_company instance);
    partial void InsertBS_resume(BS_resume instance);
    partial void UpdateBS_resume(BS_resume instance);
    partial void DeleteBS_resume(BS_resume instance);
    #endregion
		
		public BSDataClasseDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["网络招聘ConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BSDataClasseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BSDataClasseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BSDataClasseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BSDataClasseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BS_person> BS_person
		{
			get
			{
				return this.GetTable<BS_person>();
			}
		}
		
		public System.Data.Linq.Table<BS_job_resume> BS_job_resume
		{
			get
			{
				return this.GetTable<BS_job_resume>();
			}
		}
		
		public System.Data.Linq.Table<BS_rwork> BS_rwork
		{
			get
			{
				return this.GetTable<BS_rwork>();
			}
		}
		
		public System.Data.Linq.Table<BS_redu> BS_redu
		{
			get
			{
				return this.GetTable<BS_redu>();
			}
		}
		
		public System.Data.Linq.Table<BS_job> BS_job
		{
			get
			{
				return this.GetTable<BS_job>();
			}
		}
		
		public System.Data.Linq.Table<BS_c_info> BS_c_info
		{
			get
			{
				return this.GetTable<BS_c_info>();
			}
		}
		
		public System.Data.Linq.Table<BS_company> BS_company
		{
			get
			{
				return this.GetTable<BS_company>();
			}
		}
		
		public System.Data.Linq.Table<BS_resume> BS_resume
		{
			get
			{
				return this.GetTable<BS_resume>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BS_person")]
	public partial class BS_person : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _p_psw;
		
		private string _p_email;
		
		private EntitySet<BS_resume> _BS_resume;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void Onp_pswChanging(string value);
    partial void Onp_pswChanged();
    partial void Onp_emailChanging(string value);
    partial void Onp_emailChanged();
    #endregion
		
		public BS_person()
		{
			this._BS_resume = new EntitySet<BS_resume>(new Action<BS_resume>(this.attach_BS_resume), new Action<BS_resume>(this.detach_BS_resume));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_p_psw", DbType="VarChar(50)")]
		public string p_psw
		{
			get
			{
				return this._p_psw;
			}
			set
			{
				if ((this._p_psw != value))
				{
					this.Onp_pswChanging(value);
					this.SendPropertyChanging();
					this._p_psw = value;
					this.SendPropertyChanged("p_psw");
					this.Onp_pswChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_p_email", DbType="VarChar(50)")]
		public string p_email
		{
			get
			{
				return this._p_email;
			}
			set
			{
				if ((this._p_email != value))
				{
					this.Onp_emailChanging(value);
					this.SendPropertyChanging();
					this._p_email = value;
					this.SendPropertyChanged("p_email");
					this.Onp_emailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BS_person_BS_resume", Storage="_BS_resume", ThisKey="ID", OtherKey="pID")]
		public EntitySet<BS_resume> BS_resume
		{
			get
			{
				return this._BS_resume;
			}
			set
			{
				this._BS_resume.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BS_resume(BS_resume entity)
		{
			this.SendPropertyChanging();
			entity.BS_person = this;
		}
		
		private void detach_BS_resume(BS_resume entity)
		{
			this.SendPropertyChanging();
			entity.BS_person = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BS_job_resume")]
	public partial class BS_job_resume : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _rID;
		
		private System.Nullable<int> _jID;
		
		private EntityRef<BS_job> _BS_job;
		
		private EntityRef<BS_resume> _BS_resume;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnrIDChanging(System.Nullable<int> value);
    partial void OnrIDChanged();
    partial void OnjIDChanging(System.Nullable<int> value);
    partial void OnjIDChanged();
    #endregion
		
		public BS_job_resume()
		{
			this._BS_job = default(EntityRef<BS_job>);
			this._BS_resume = default(EntityRef<BS_resume>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rID", DbType="Int")]
		public System.Nullable<int> rID
		{
			get
			{
				return this._rID;
			}
			set
			{
				if ((this._rID != value))
				{
					if (this._BS_resume.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnrIDChanging(value);
					this.SendPropertyChanging();
					this._rID = value;
					this.SendPropertyChanged("rID");
					this.OnrIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jID", DbType="Int")]
		public System.Nullable<int> jID
		{
			get
			{
				return this._jID;
			}
			set
			{
				if ((this._jID != value))
				{
					if (this._BS_job.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnjIDChanging(value);
					this.SendPropertyChanging();
					this._jID = value;
					this.SendPropertyChanged("jID");
					this.OnjIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BS_job_BS_job_resume", Storage="_BS_job", ThisKey="jID", OtherKey="ID", IsForeignKey=true, DeleteRule="CASCADE")]
		public BS_job BS_job
		{
			get
			{
				return this._BS_job.Entity;
			}
			set
			{
				BS_job previousValue = this._BS_job.Entity;
				if (((previousValue != value) 
							|| (this._BS_job.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BS_job.Entity = null;
						previousValue.BS_job_resume.Remove(this);
					}
					this._BS_job.Entity = value;
					if ((value != null))
					{
						value.BS_job_resume.Add(this);
						this._jID = value.ID;
					}
					else
					{
						this._jID = default(Nullable<int>);
					}
					this.SendPropertyChanged("BS_job");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BS_resume_BS_job_resume", Storage="_BS_resume", ThisKey="rID", OtherKey="ID", IsForeignKey=true, DeleteRule="CASCADE")]
		public BS_resume BS_resume
		{
			get
			{
				return this._BS_resume.Entity;
			}
			set
			{
				BS_resume previousValue = this._BS_resume.Entity;
				if (((previousValue != value) 
							|| (this._BS_resume.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BS_resume.Entity = null;
						previousValue.BS_job_resume.Remove(this);
					}
					this._BS_resume.Entity = value;
					if ((value != null))
					{
						value.BS_job_resume.Add(this);
						this._rID = value.ID;
					}
					else
					{
						this._rID = default(Nullable<int>);
					}
					this.SendPropertyChanged("BS_resume");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BS_rwork")]
	public partial class BS_rwork : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _rID;
		
		private string _w_s_time;
		
		private string _w_e_time;
		
		private string _w_company;
		
		private string _w_zhiwei;
		
		private string _w_bumen;
		
		private string _w_miaoshu;
		
		private EntityRef<BS_resume> _BS_resume;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnrIDChanging(System.Nullable<int> value);
    partial void OnrIDChanged();
    partial void Onw_s_timeChanging(string value);
    partial void Onw_s_timeChanged();
    partial void Onw_e_timeChanging(string value);
    partial void Onw_e_timeChanged();
    partial void Onw_companyChanging(string value);
    partial void Onw_companyChanged();
    partial void Onw_zhiweiChanging(string value);
    partial void Onw_zhiweiChanged();
    partial void Onw_bumenChanging(string value);
    partial void Onw_bumenChanged();
    partial void Onw_miaoshuChanging(string value);
    partial void Onw_miaoshuChanged();
    #endregion
		
		public BS_rwork()
		{
			this._BS_resume = default(EntityRef<BS_resume>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rID", DbType="Int")]
		public System.Nullable<int> rID
		{
			get
			{
				return this._rID;
			}
			set
			{
				if ((this._rID != value))
				{
					if (this._BS_resume.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnrIDChanging(value);
					this.SendPropertyChanging();
					this._rID = value;
					this.SendPropertyChanged("rID");
					this.OnrIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_w_s_time", DbType="VarChar(50)")]
		public string w_s_time
		{
			get
			{
				return this._w_s_time;
			}
			set
			{
				if ((this._w_s_time != value))
				{
					this.Onw_s_timeChanging(value);
					this.SendPropertyChanging();
					this._w_s_time = value;
					this.SendPropertyChanged("w_s_time");
					this.Onw_s_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_w_e_time", DbType="VarChar(50)")]
		public string w_e_time
		{
			get
			{
				return this._w_e_time;
			}
			set
			{
				if ((this._w_e_time != value))
				{
					this.Onw_e_timeChanging(value);
					this.SendPropertyChanging();
					this._w_e_time = value;
					this.SendPropertyChanged("w_e_time");
					this.Onw_e_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_w_company", DbType="VarChar(50)")]
		public string w_company
		{
			get
			{
				return this._w_company;
			}
			set
			{
				if ((this._w_company != value))
				{
					this.Onw_companyChanging(value);
					this.SendPropertyChanging();
					this._w_company = value;
					this.SendPropertyChanged("w_company");
					this.Onw_companyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_w_zhiwei", DbType="VarChar(50)")]
		public string w_zhiwei
		{
			get
			{
				return this._w_zhiwei;
			}
			set
			{
				if ((this._w_zhiwei != value))
				{
					this.Onw_zhiweiChanging(value);
					this.SendPropertyChanging();
					this._w_zhiwei = value;
					this.SendPropertyChanged("w_zhiwei");
					this.Onw_zhiweiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_w_bumen", DbType="VarChar(50)")]
		public string w_bumen
		{
			get
			{
				return this._w_bumen;
			}
			set
			{
				if ((this._w_bumen != value))
				{
					this.Onw_bumenChanging(value);
					this.SendPropertyChanging();
					this._w_bumen = value;
					this.SendPropertyChanged("w_bumen");
					this.Onw_bumenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_w_miaoshu", DbType="VarChar(200)")]
		public string w_miaoshu
		{
			get
			{
				return this._w_miaoshu;
			}
			set
			{
				if ((this._w_miaoshu != value))
				{
					this.Onw_miaoshuChanging(value);
					this.SendPropertyChanging();
					this._w_miaoshu = value;
					this.SendPropertyChanged("w_miaoshu");
					this.Onw_miaoshuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BS_resume_BS_rwork", Storage="_BS_resume", ThisKey="rID", OtherKey="ID", IsForeignKey=true, DeleteRule="CASCADE")]
		public BS_resume BS_resume
		{
			get
			{
				return this._BS_resume.Entity;
			}
			set
			{
				BS_resume previousValue = this._BS_resume.Entity;
				if (((previousValue != value) 
							|| (this._BS_resume.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BS_resume.Entity = null;
						previousValue.BS_rwork.Remove(this);
					}
					this._BS_resume.Entity = value;
					if ((value != null))
					{
						value.BS_rwork.Add(this);
						this._rID = value.ID;
					}
					else
					{
						this._rID = default(Nullable<int>);
					}
					this.SendPropertyChanged("BS_resume");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BS_redu")]
	public partial class BS_redu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _rID;
		
		private string _e_s_time;
		
		private string _e_e_time;
		
		private string _e_school;
		
		private string _e_major;
		
		private string _e_degree;
		
		private string _e_miaoshu;
		
		private EntityRef<BS_resume> _BS_resume;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnrIDChanging(System.Nullable<int> value);
    partial void OnrIDChanged();
    partial void One_s_timeChanging(string value);
    partial void One_s_timeChanged();
    partial void One_e_timeChanging(string value);
    partial void One_e_timeChanged();
    partial void One_schoolChanging(string value);
    partial void One_schoolChanged();
    partial void One_majorChanging(string value);
    partial void One_majorChanged();
    partial void One_degreeChanging(string value);
    partial void One_degreeChanged();
    partial void One_miaoshuChanging(string value);
    partial void One_miaoshuChanged();
    #endregion
		
		public BS_redu()
		{
			this._BS_resume = default(EntityRef<BS_resume>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rID", DbType="Int")]
		public System.Nullable<int> rID
		{
			get
			{
				return this._rID;
			}
			set
			{
				if ((this._rID != value))
				{
					if (this._BS_resume.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnrIDChanging(value);
					this.SendPropertyChanging();
					this._rID = value;
					this.SendPropertyChanged("rID");
					this.OnrIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_e_s_time", DbType="VarChar(50)")]
		public string e_s_time
		{
			get
			{
				return this._e_s_time;
			}
			set
			{
				if ((this._e_s_time != value))
				{
					this.One_s_timeChanging(value);
					this.SendPropertyChanging();
					this._e_s_time = value;
					this.SendPropertyChanged("e_s_time");
					this.One_s_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_e_e_time", DbType="VarChar(50)")]
		public string e_e_time
		{
			get
			{
				return this._e_e_time;
			}
			set
			{
				if ((this._e_e_time != value))
				{
					this.One_e_timeChanging(value);
					this.SendPropertyChanging();
					this._e_e_time = value;
					this.SendPropertyChanged("e_e_time");
					this.One_e_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_e_school", DbType="VarChar(50)")]
		public string e_school
		{
			get
			{
				return this._e_school;
			}
			set
			{
				if ((this._e_school != value))
				{
					this.One_schoolChanging(value);
					this.SendPropertyChanging();
					this._e_school = value;
					this.SendPropertyChanged("e_school");
					this.One_schoolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_e_major", DbType="VarChar(50)")]
		public string e_major
		{
			get
			{
				return this._e_major;
			}
			set
			{
				if ((this._e_major != value))
				{
					this.One_majorChanging(value);
					this.SendPropertyChanging();
					this._e_major = value;
					this.SendPropertyChanged("e_major");
					this.One_majorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_e_degree", DbType="VarChar(50)")]
		public string e_degree
		{
			get
			{
				return this._e_degree;
			}
			set
			{
				if ((this._e_degree != value))
				{
					this.One_degreeChanging(value);
					this.SendPropertyChanging();
					this._e_degree = value;
					this.SendPropertyChanged("e_degree");
					this.One_degreeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_e_miaoshu", DbType="VarChar(200)")]
		public string e_miaoshu
		{
			get
			{
				return this._e_miaoshu;
			}
			set
			{
				if ((this._e_miaoshu != value))
				{
					this.One_miaoshuChanging(value);
					this.SendPropertyChanging();
					this._e_miaoshu = value;
					this.SendPropertyChanged("e_miaoshu");
					this.One_miaoshuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BS_resume_BS_redu", Storage="_BS_resume", ThisKey="rID", OtherKey="ID", IsForeignKey=true, DeleteRule="CASCADE")]
		public BS_resume BS_resume
		{
			get
			{
				return this._BS_resume.Entity;
			}
			set
			{
				BS_resume previousValue = this._BS_resume.Entity;
				if (((previousValue != value) 
							|| (this._BS_resume.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BS_resume.Entity = null;
						previousValue.BS_redu.Remove(this);
					}
					this._BS_resume.Entity = value;
					if ((value != null))
					{
						value.BS_redu.Add(this);
						this._rID = value.ID;
					}
					else
					{
						this._rID = default(Nullable<int>);
					}
					this.SendPropertyChanged("BS_resume");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BS_job")]
	public partial class BS_job : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _cID;
		
		private string _j_name;
		
		private string _j_time;
		
		private string _j_city;
		
		private string _j_renshu;
		
		private string _j_nianxian;
		
		private string _j_degree;
		
		private string _j_xinshui;
		
		private string _j_miaoshu;
		
		private EntitySet<BS_job_resume> _BS_job_resume;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OncIDChanging(System.Nullable<int> value);
    partial void OncIDChanged();
    partial void Onj_nameChanging(string value);
    partial void Onj_nameChanged();
    partial void Onj_timeChanging(string value);
    partial void Onj_timeChanged();
    partial void Onj_cityChanging(string value);
    partial void Onj_cityChanged();
    partial void Onj_renshuChanging(string value);
    partial void Onj_renshuChanged();
    partial void Onj_nianxianChanging(string value);
    partial void Onj_nianxianChanged();
    partial void Onj_degreeChanging(string value);
    partial void Onj_degreeChanged();
    partial void Onj_xinshuiChanging(string value);
    partial void Onj_xinshuiChanged();
    partial void Onj_miaoshuChanging(string value);
    partial void Onj_miaoshuChanged();
    #endregion
		
		public BS_job()
		{
			this._BS_job_resume = new EntitySet<BS_job_resume>(new Action<BS_job_resume>(this.attach_BS_job_resume), new Action<BS_job_resume>(this.detach_BS_job_resume));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cID", DbType="Int")]
		public System.Nullable<int> cID
		{
			get
			{
				return this._cID;
			}
			set
			{
				if ((this._cID != value))
				{
					this.OncIDChanging(value);
					this.SendPropertyChanging();
					this._cID = value;
					this.SendPropertyChanged("cID");
					this.OncIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_j_name", DbType="VarChar(50)")]
		public string j_name
		{
			get
			{
				return this._j_name;
			}
			set
			{
				if ((this._j_name != value))
				{
					this.Onj_nameChanging(value);
					this.SendPropertyChanging();
					this._j_name = value;
					this.SendPropertyChanged("j_name");
					this.Onj_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_j_time", DbType="VarChar(50)")]
		public string j_time
		{
			get
			{
				return this._j_time;
			}
			set
			{
				if ((this._j_time != value))
				{
					this.Onj_timeChanging(value);
					this.SendPropertyChanging();
					this._j_time = value;
					this.SendPropertyChanged("j_time");
					this.Onj_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_j_city", DbType="VarChar(50)")]
		public string j_city
		{
			get
			{
				return this._j_city;
			}
			set
			{
				if ((this._j_city != value))
				{
					this.Onj_cityChanging(value);
					this.SendPropertyChanging();
					this._j_city = value;
					this.SendPropertyChanged("j_city");
					this.Onj_cityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_j_renshu", DbType="VarChar(50)")]
		public string j_renshu
		{
			get
			{
				return this._j_renshu;
			}
			set
			{
				if ((this._j_renshu != value))
				{
					this.Onj_renshuChanging(value);
					this.SendPropertyChanging();
					this._j_renshu = value;
					this.SendPropertyChanged("j_renshu");
					this.Onj_renshuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_j_nianxian", DbType="VarChar(50)")]
		public string j_nianxian
		{
			get
			{
				return this._j_nianxian;
			}
			set
			{
				if ((this._j_nianxian != value))
				{
					this.Onj_nianxianChanging(value);
					this.SendPropertyChanging();
					this._j_nianxian = value;
					this.SendPropertyChanged("j_nianxian");
					this.Onj_nianxianChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_j_degree", DbType="VarChar(50)")]
		public string j_degree
		{
			get
			{
				return this._j_degree;
			}
			set
			{
				if ((this._j_degree != value))
				{
					this.Onj_degreeChanging(value);
					this.SendPropertyChanging();
					this._j_degree = value;
					this.SendPropertyChanged("j_degree");
					this.Onj_degreeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_j_xinshui", DbType="VarChar(50)")]
		public string j_xinshui
		{
			get
			{
				return this._j_xinshui;
			}
			set
			{
				if ((this._j_xinshui != value))
				{
					this.Onj_xinshuiChanging(value);
					this.SendPropertyChanging();
					this._j_xinshui = value;
					this.SendPropertyChanged("j_xinshui");
					this.Onj_xinshuiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_j_miaoshu", DbType="VarChar(2000)")]
		public string j_miaoshu
		{
			get
			{
				return this._j_miaoshu;
			}
			set
			{
				if ((this._j_miaoshu != value))
				{
					this.Onj_miaoshuChanging(value);
					this.SendPropertyChanging();
					this._j_miaoshu = value;
					this.SendPropertyChanged("j_miaoshu");
					this.Onj_miaoshuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BS_job_BS_job_resume", Storage="_BS_job_resume", ThisKey="ID", OtherKey="jID")]
		public EntitySet<BS_job_resume> BS_job_resume
		{
			get
			{
				return this._BS_job_resume;
			}
			set
			{
				this._BS_job_resume.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BS_job_resume(BS_job_resume entity)
		{
			this.SendPropertyChanging();
			entity.BS_job = this;
		}
		
		private void detach_BS_job_resume(BS_job_resume entity)
		{
			this.SendPropertyChanging();
			entity.BS_job = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BS_c_info")]
	public partial class BS_c_info : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _cID;
		
		private string _c_name;
		
		private string _c_xingzhi;
		
		private string _c_hangye;
		
		private string _c_guimo;
		
		private string _c_tellphone;
		
		private string _c_email;
		
		private string _c_website;
		
		private string _c_address;
		
		private string _c_jianjie;
		
		private EntityRef<BS_company> _BS_company;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OncIDChanging(System.Nullable<int> value);
    partial void OncIDChanged();
    partial void Onc_nameChanging(string value);
    partial void Onc_nameChanged();
    partial void Onc_xingzhiChanging(string value);
    partial void Onc_xingzhiChanged();
    partial void Onc_hangyeChanging(string value);
    partial void Onc_hangyeChanged();
    partial void Onc_guimoChanging(string value);
    partial void Onc_guimoChanged();
    partial void Onc_tellphoneChanging(string value);
    partial void Onc_tellphoneChanged();
    partial void Onc_emailChanging(string value);
    partial void Onc_emailChanged();
    partial void Onc_websiteChanging(string value);
    partial void Onc_websiteChanged();
    partial void Onc_addressChanging(string value);
    partial void Onc_addressChanged();
    partial void Onc_jianjieChanging(string value);
    partial void Onc_jianjieChanged();
    #endregion
		
		public BS_c_info()
		{
			this._BS_company = default(EntityRef<BS_company>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cID", DbType="Int")]
		public System.Nullable<int> cID
		{
			get
			{
				return this._cID;
			}
			set
			{
				if ((this._cID != value))
				{
					if (this._BS_company.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncIDChanging(value);
					this.SendPropertyChanging();
					this._cID = value;
					this.SendPropertyChanged("cID");
					this.OncIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_name", DbType="VarChar(100)")]
		public string c_name
		{
			get
			{
				return this._c_name;
			}
			set
			{
				if ((this._c_name != value))
				{
					this.Onc_nameChanging(value);
					this.SendPropertyChanging();
					this._c_name = value;
					this.SendPropertyChanged("c_name");
					this.Onc_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_xingzhi", DbType="VarChar(50)")]
		public string c_xingzhi
		{
			get
			{
				return this._c_xingzhi;
			}
			set
			{
				if ((this._c_xingzhi != value))
				{
					this.Onc_xingzhiChanging(value);
					this.SendPropertyChanging();
					this._c_xingzhi = value;
					this.SendPropertyChanged("c_xingzhi");
					this.Onc_xingzhiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_hangye", DbType="VarChar(50)")]
		public string c_hangye
		{
			get
			{
				return this._c_hangye;
			}
			set
			{
				if ((this._c_hangye != value))
				{
					this.Onc_hangyeChanging(value);
					this.SendPropertyChanging();
					this._c_hangye = value;
					this.SendPropertyChanged("c_hangye");
					this.Onc_hangyeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_guimo", DbType="VarChar(50)")]
		public string c_guimo
		{
			get
			{
				return this._c_guimo;
			}
			set
			{
				if ((this._c_guimo != value))
				{
					this.Onc_guimoChanging(value);
					this.SendPropertyChanging();
					this._c_guimo = value;
					this.SendPropertyChanged("c_guimo");
					this.Onc_guimoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_tellphone", DbType="VarChar(50)")]
		public string c_tellphone
		{
			get
			{
				return this._c_tellphone;
			}
			set
			{
				if ((this._c_tellphone != value))
				{
					this.Onc_tellphoneChanging(value);
					this.SendPropertyChanging();
					this._c_tellphone = value;
					this.SendPropertyChanged("c_tellphone");
					this.Onc_tellphoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_email", DbType="VarChar(100)")]
		public string c_email
		{
			get
			{
				return this._c_email;
			}
			set
			{
				if ((this._c_email != value))
				{
					this.Onc_emailChanging(value);
					this.SendPropertyChanging();
					this._c_email = value;
					this.SendPropertyChanged("c_email");
					this.Onc_emailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_website", DbType="VarChar(200)")]
		public string c_website
		{
			get
			{
				return this._c_website;
			}
			set
			{
				if ((this._c_website != value))
				{
					this.Onc_websiteChanging(value);
					this.SendPropertyChanging();
					this._c_website = value;
					this.SendPropertyChanged("c_website");
					this.Onc_websiteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_address", DbType="VarChar(200)")]
		public string c_address
		{
			get
			{
				return this._c_address;
			}
			set
			{
				if ((this._c_address != value))
				{
					this.Onc_addressChanging(value);
					this.SendPropertyChanging();
					this._c_address = value;
					this.SendPropertyChanged("c_address");
					this.Onc_addressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_jianjie", DbType="VarChar(2000)")]
		public string c_jianjie
		{
			get
			{
				return this._c_jianjie;
			}
			set
			{
				if ((this._c_jianjie != value))
				{
					this.Onc_jianjieChanging(value);
					this.SendPropertyChanging();
					this._c_jianjie = value;
					this.SendPropertyChanged("c_jianjie");
					this.Onc_jianjieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BS_company_BS_c_info", Storage="_BS_company", ThisKey="cID", OtherKey="ID", IsForeignKey=true)]
		public BS_company BS_company
		{
			get
			{
				return this._BS_company.Entity;
			}
			set
			{
				BS_company previousValue = this._BS_company.Entity;
				if (((previousValue != value) 
							|| (this._BS_company.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BS_company.Entity = null;
						previousValue.BS_c_info.Remove(this);
					}
					this._BS_company.Entity = value;
					if ((value != null))
					{
						value.BS_c_info.Add(this);
						this._cID = value.ID;
					}
					else
					{
						this._cID = default(Nullable<int>);
					}
					this.SendPropertyChanged("BS_company");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BS_company")]
	public partial class BS_company : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _c_email;
		
		private string _c_psw;
		
		private string _c_name;
		
		private EntitySet<BS_c_info> _BS_c_info;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void Onc_emailChanging(string value);
    partial void Onc_emailChanged();
    partial void Onc_pswChanging(string value);
    partial void Onc_pswChanged();
    partial void Onc_nameChanging(string value);
    partial void Onc_nameChanged();
    #endregion
		
		public BS_company()
		{
			this._BS_c_info = new EntitySet<BS_c_info>(new Action<BS_c_info>(this.attach_BS_c_info), new Action<BS_c_info>(this.detach_BS_c_info));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_email", DbType="VarChar(50)")]
		public string c_email
		{
			get
			{
				return this._c_email;
			}
			set
			{
				if ((this._c_email != value))
				{
					this.Onc_emailChanging(value);
					this.SendPropertyChanging();
					this._c_email = value;
					this.SendPropertyChanged("c_email");
					this.Onc_emailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_psw", DbType="VarChar(50)")]
		public string c_psw
		{
			get
			{
				return this._c_psw;
			}
			set
			{
				if ((this._c_psw != value))
				{
					this.Onc_pswChanging(value);
					this.SendPropertyChanging();
					this._c_psw = value;
					this.SendPropertyChanged("c_psw");
					this.Onc_pswChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_name", DbType="VarChar(100)")]
		public string c_name
		{
			get
			{
				return this._c_name;
			}
			set
			{
				if ((this._c_name != value))
				{
					this.Onc_nameChanging(value);
					this.SendPropertyChanging();
					this._c_name = value;
					this.SendPropertyChanged("c_name");
					this.Onc_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BS_company_BS_c_info", Storage="_BS_c_info", ThisKey="ID", OtherKey="cID")]
		public EntitySet<BS_c_info> BS_c_info
		{
			get
			{
				return this._BS_c_info;
			}
			set
			{
				this._BS_c_info.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BS_c_info(BS_c_info entity)
		{
			this.SendPropertyChanging();
			entity.BS_company = this;
		}
		
		private void detach_BS_c_info(BS_c_info entity)
		{
			this.SendPropertyChanging();
			entity.BS_company = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BS_resume")]
	public partial class BS_resume : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _pID;
		
		private string _r_name;
		
		private string _p_name;
		
		private string _p_sex;
		
		private string _p_age;
		
		private string _p_degree;
		
		private string _p_phone;
		
		private string _p_email;
		
		private string _p_height;
		
		private string _p_jiguan;
		
		private string _p_dangpai;
		
		private string _p_hunfou;
		
		private string _p_address;
		
		private string _r_time;
		
		private EntitySet<BS_job_resume> _BS_job_resume;
		
		private EntitySet<BS_rwork> _BS_rwork;
		
		private EntitySet<BS_redu> _BS_redu;
		
		private EntityRef<BS_person> _BS_person;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnpIDChanging(System.Nullable<int> value);
    partial void OnpIDChanged();
    partial void Onr_nameChanging(string value);
    partial void Onr_nameChanged();
    partial void Onp_nameChanging(string value);
    partial void Onp_nameChanged();
    partial void Onp_sexChanging(string value);
    partial void Onp_sexChanged();
    partial void Onp_ageChanging(string value);
    partial void Onp_ageChanged();
    partial void Onp_degreeChanging(string value);
    partial void Onp_degreeChanged();
    partial void Onp_phoneChanging(string value);
    partial void Onp_phoneChanged();
    partial void Onp_emailChanging(string value);
    partial void Onp_emailChanged();
    partial void Onp_heightChanging(string value);
    partial void Onp_heightChanged();
    partial void Onp_jiguanChanging(string value);
    partial void Onp_jiguanChanged();
    partial void Onp_dangpaiChanging(string value);
    partial void Onp_dangpaiChanged();
    partial void Onp_hunfouChanging(string value);
    partial void Onp_hunfouChanged();
    partial void Onp_addressChanging(string value);
    partial void Onp_addressChanged();
    partial void Onr_timeChanging(string value);
    partial void Onr_timeChanged();
    #endregion
		
		public BS_resume()
		{
			this._BS_job_resume = new EntitySet<BS_job_resume>(new Action<BS_job_resume>(this.attach_BS_job_resume), new Action<BS_job_resume>(this.detach_BS_job_resume));
			this._BS_rwork = new EntitySet<BS_rwork>(new Action<BS_rwork>(this.attach_BS_rwork), new Action<BS_rwork>(this.detach_BS_rwork));
			this._BS_redu = new EntitySet<BS_redu>(new Action<BS_redu>(this.attach_BS_redu), new Action<BS_redu>(this.detach_BS_redu));
			this._BS_person = default(EntityRef<BS_person>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pID", DbType="Int")]
		public System.Nullable<int> pID
		{
			get
			{
				return this._pID;
			}
			set
			{
				if ((this._pID != value))
				{
					if (this._BS_person.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnpIDChanging(value);
					this.SendPropertyChanging();
					this._pID = value;
					this.SendPropertyChanged("pID");
					this.OnpIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_r_name", DbType="VarChar(50)")]
		public string r_name
		{
			get
			{
				return this._r_name;
			}
			set
			{
				if ((this._r_name != value))
				{
					this.Onr_nameChanging(value);
					this.SendPropertyChanging();
					this._r_name = value;
					this.SendPropertyChanged("r_name");
					this.Onr_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_p_name", DbType="VarChar(50)")]
		public string p_name
		{
			get
			{
				return this._p_name;
			}
			set
			{
				if ((this._p_name != value))
				{
					this.Onp_nameChanging(value);
					this.SendPropertyChanging();
					this._p_name = value;
					this.SendPropertyChanged("p_name");
					this.Onp_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_p_sex", DbType="VarChar(50)")]
		public string p_sex
		{
			get
			{
				return this._p_sex;
			}
			set
			{
				if ((this._p_sex != value))
				{
					this.Onp_sexChanging(value);
					this.SendPropertyChanging();
					this._p_sex = value;
					this.SendPropertyChanged("p_sex");
					this.Onp_sexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_p_age", DbType="VarChar(50)")]
		public string p_age
		{
			get
			{
				return this._p_age;
			}
			set
			{
				if ((this._p_age != value))
				{
					this.Onp_ageChanging(value);
					this.SendPropertyChanging();
					this._p_age = value;
					this.SendPropertyChanged("p_age");
					this.Onp_ageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_p_degree", DbType="VarChar(50)")]
		public string p_degree
		{
			get
			{
				return this._p_degree;
			}
			set
			{
				if ((this._p_degree != value))
				{
					this.Onp_degreeChanging(value);
					this.SendPropertyChanging();
					this._p_degree = value;
					this.SendPropertyChanged("p_degree");
					this.Onp_degreeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_p_phone", DbType="VarChar(50)")]
		public string p_phone
		{
			get
			{
				return this._p_phone;
			}
			set
			{
				if ((this._p_phone != value))
				{
					this.Onp_phoneChanging(value);
					this.SendPropertyChanging();
					this._p_phone = value;
					this.SendPropertyChanged("p_phone");
					this.Onp_phoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_p_email", DbType="VarChar(50)")]
		public string p_email
		{
			get
			{
				return this._p_email;
			}
			set
			{
				if ((this._p_email != value))
				{
					this.Onp_emailChanging(value);
					this.SendPropertyChanging();
					this._p_email = value;
					this.SendPropertyChanged("p_email");
					this.Onp_emailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_p_height", DbType="VarChar(20)")]
		public string p_height
		{
			get
			{
				return this._p_height;
			}
			set
			{
				if ((this._p_height != value))
				{
					this.Onp_heightChanging(value);
					this.SendPropertyChanging();
					this._p_height = value;
					this.SendPropertyChanged("p_height");
					this.Onp_heightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_p_jiguan", DbType="VarChar(50)")]
		public string p_jiguan
		{
			get
			{
				return this._p_jiguan;
			}
			set
			{
				if ((this._p_jiguan != value))
				{
					this.Onp_jiguanChanging(value);
					this.SendPropertyChanging();
					this._p_jiguan = value;
					this.SendPropertyChanged("p_jiguan");
					this.Onp_jiguanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_p_dangpai", DbType="VarChar(50)")]
		public string p_dangpai
		{
			get
			{
				return this._p_dangpai;
			}
			set
			{
				if ((this._p_dangpai != value))
				{
					this.Onp_dangpaiChanging(value);
					this.SendPropertyChanging();
					this._p_dangpai = value;
					this.SendPropertyChanged("p_dangpai");
					this.Onp_dangpaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_p_hunfou", DbType="VarChar(50)")]
		public string p_hunfou
		{
			get
			{
				return this._p_hunfou;
			}
			set
			{
				if ((this._p_hunfou != value))
				{
					this.Onp_hunfouChanging(value);
					this.SendPropertyChanging();
					this._p_hunfou = value;
					this.SendPropertyChanged("p_hunfou");
					this.Onp_hunfouChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_p_address", DbType="VarChar(100)")]
		public string p_address
		{
			get
			{
				return this._p_address;
			}
			set
			{
				if ((this._p_address != value))
				{
					this.Onp_addressChanging(value);
					this.SendPropertyChanging();
					this._p_address = value;
					this.SendPropertyChanged("p_address");
					this.Onp_addressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_r_time", DbType="VarChar(50)")]
		public string r_time
		{
			get
			{
				return this._r_time;
			}
			set
			{
				if ((this._r_time != value))
				{
					this.Onr_timeChanging(value);
					this.SendPropertyChanging();
					this._r_time = value;
					this.SendPropertyChanged("r_time");
					this.Onr_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BS_resume_BS_job_resume", Storage="_BS_job_resume", ThisKey="ID", OtherKey="rID")]
		public EntitySet<BS_job_resume> BS_job_resume
		{
			get
			{
				return this._BS_job_resume;
			}
			set
			{
				this._BS_job_resume.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BS_resume_BS_rwork", Storage="_BS_rwork", ThisKey="ID", OtherKey="rID")]
		public EntitySet<BS_rwork> BS_rwork
		{
			get
			{
				return this._BS_rwork;
			}
			set
			{
				this._BS_rwork.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BS_resume_BS_redu", Storage="_BS_redu", ThisKey="ID", OtherKey="rID")]
		public EntitySet<BS_redu> BS_redu
		{
			get
			{
				return this._BS_redu;
			}
			set
			{
				this._BS_redu.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BS_person_BS_resume", Storage="_BS_person", ThisKey="pID", OtherKey="ID", IsForeignKey=true)]
		public BS_person BS_person
		{
			get
			{
				return this._BS_person.Entity;
			}
			set
			{
				BS_person previousValue = this._BS_person.Entity;
				if (((previousValue != value) 
							|| (this._BS_person.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BS_person.Entity = null;
						previousValue.BS_resume.Remove(this);
					}
					this._BS_person.Entity = value;
					if ((value != null))
					{
						value.BS_resume.Add(this);
						this._pID = value.ID;
					}
					else
					{
						this._pID = default(Nullable<int>);
					}
					this.SendPropertyChanged("BS_person");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BS_job_resume(BS_job_resume entity)
		{
			this.SendPropertyChanging();
			entity.BS_resume = this;
		}
		
		private void detach_BS_job_resume(BS_job_resume entity)
		{
			this.SendPropertyChanging();
			entity.BS_resume = null;
		}
		
		private void attach_BS_rwork(BS_rwork entity)
		{
			this.SendPropertyChanging();
			entity.BS_resume = this;
		}
		
		private void detach_BS_rwork(BS_rwork entity)
		{
			this.SendPropertyChanging();
			entity.BS_resume = null;
		}
		
		private void attach_BS_redu(BS_redu entity)
		{
			this.SendPropertyChanging();
			entity.BS_resume = this;
		}
		
		private void detach_BS_redu(BS_redu entity)
		{
			this.SendPropertyChanging();
			entity.BS_resume = null;
		}
	}
}
#pragma warning restore 1591
